version: '{build}'
init:
- ps: |
    function craft() {
        & C:\python36\python.exe "C:\CraftMaster\$env:TARGET\craft\bin\craft.py" $args
    }

install:
- ps: |
    $ErrorActionPreference="Continue"
    mkdir C:\CraftMaster
    & git clone https://github.com/TheOneRing/CraftMaster.git C:\CraftMaster\CraftMaster
    & C:\python36\python.exe C:\CraftMaster\CraftMaster\CraftMaster.py --config $env:APPVEYOR_BUILD_FOLDER\appveyor.ini --target $env:TARGET
    $ErrorActionPreference="Stop"


build_script:
- ps: |
    craft --no-cache --src-dir $env:APPVEYOR_BUILD_FOLDER charm

test_script:
- ps: |
    craft --src-dir $env:APPVEYOR_BUILD_FOLDER --test charm


on_success:
- ps: |
    craft --src-dir $env:APPVEYOR_BUILD_FOLDER --package charm
    Get-ChildItem C:\CraftMaster\$env:TARGET\tmp\* | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

on_finish:
- ps: |
    Get-ChildItem $env:USERPROFILE\.craft\* | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
    Push-AppveyorArtifact C:\CraftMaster\$env:TARGET\etc\kdesettings.ini.dump




environment:
    matrix:
    - TARGET: msvc2015x64
    - TARGET: msvc2015x86
    - TARGET: mingw
